package com.techidea.dblibrary.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.techidea.dblibrary.db.PrintDataItem;
import com.techidea.dblibrary.db.Item;
import com.techidea.dblibrary.db.ListItem;

import com.techidea.dblibrary.db.PrintDataItemDao;
import com.techidea.dblibrary.db.ItemDao;
import com.techidea.dblibrary.db.ListItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig printDataItemDaoConfig;
    private final DaoConfig itemDaoConfig;
    private final DaoConfig listItemDaoConfig;

    private final PrintDataItemDao printDataItemDao;
    private final ItemDao itemDao;
    private final ListItemDao listItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        printDataItemDaoConfig = daoConfigMap.get(PrintDataItemDao.class).clone();
        printDataItemDaoConfig.initIdentityScope(type);

        itemDaoConfig = daoConfigMap.get(ItemDao.class).clone();
        itemDaoConfig.initIdentityScope(type);

        listItemDaoConfig = daoConfigMap.get(ListItemDao.class).clone();
        listItemDaoConfig.initIdentityScope(type);

        printDataItemDao = new PrintDataItemDao(printDataItemDaoConfig, this);
        itemDao = new ItemDao(itemDaoConfig, this);
        listItemDao = new ListItemDao(listItemDaoConfig, this);

        registerDao(PrintDataItem.class, printDataItemDao);
        registerDao(Item.class, itemDao);
        registerDao(ListItem.class, listItemDao);
    }
    
    public void clear() {
        printDataItemDaoConfig.getIdentityScope().clear();
        itemDaoConfig.getIdentityScope().clear();
        listItemDaoConfig.getIdentityScope().clear();
    }

    public PrintDataItemDao getPrintDataItemDao() {
        return printDataItemDao;
    }

    public ItemDao getItemDao() {
        return itemDao;
    }

    public ListItemDao getListItemDao() {
        return listItemDao;
    }

}
