package com.techidea.dblibrary.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PRINT_DATA_ITEM".
 */
public class PrintDataItem {

    private Long id;
    private String printdata;
    private Integer position;
    private Integer doubleformat;
    private Integer printermode;
    private Long inserttime;

    public PrintDataItem() {
    }

    public PrintDataItem(Long id) {
        this.id = id;
    }

    public PrintDataItem(Long id, String printdata, Integer position, Integer doubleformat, Integer printermode, Long inserttime) {
        this.id = id;
        this.printdata = printdata;
        this.position = position;
        this.doubleformat = doubleformat;
        this.printermode = printermode;
        this.inserttime = inserttime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPrintdata() {
        return printdata;
    }

    public void setPrintdata(String printdata) {
        this.printdata = printdata;
    }

    public Integer getPosition() {
        return position;
    }

    public void setPosition(Integer position) {
        this.position = position;
    }

    public Integer getDoubleformat() {
        return doubleformat;
    }

    public void setDoubleformat(Integer doubleformat) {
        this.doubleformat = doubleformat;
    }

    public Integer getPrintermode() {
        return printermode;
    }

    public void setPrintermode(Integer printermode) {
        this.printermode = printermode;
    }

    public Long getInserttime() {
        return inserttime;
    }

    public void setInserttime(Long inserttime) {
        this.inserttime = inserttime;
    }

}
